version: '3.8'

services:
  rabbitmq:
    container_name: rabbit-mq
    image: rabbitmq:3.10-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
    - gn-backend-net

  pedidos-db: 
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=pedido
      - POSTGRES_USER=pedido_user
      - POSTGRES_PASSWORD=pedidoGN1234

    ports:
      - "35432:5432"

    networks:
      - gn-backend-net


  order-service: 
    container_name: order-handle-service
    build:
      context: order-handle-service

    environment:
      - RABBIT_MQ_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - DB_HOST=pedidos-db
      - DB_PORT=5432
      - DB_USER=pedido_user
      - DB_NAME=pedido
      - DB_PASS=pedidoGN1234

    ports:
      - 9000:9000

    networks:
      - gn-backend-net


      

networks:
  gn-backend-net:
